### ISSUE TITLE
Why not submit PR's to original project

### ISSUE THREAD

**Issue by inxilpro** [rebing/graphql-laravel#12]
Is there a reason you didn't just submit PR's to the original `laravel-graphql` project? It looks like you're implementing some great new features, but this project has much less visibility, which means it's likely to get less bugfix contributions/etc. Why not combine efforts?

**Comment by rebing** [comment]
I initially created this package for a corporate project and we had some specific requirements, like Query/Mutation authorization, Privacy per field and SelectFields. I didn't have the time to wait and couldn't even be certain my PR's would be accepted, since the original project seemed much more general.

**Comment by inxilpro** [comment]
Makes sense. Are you OK with me porting some of your changes over to the main repo?

**Comment by rebing** [comment]
Sure :)
