### ISSUE TITLE
Migration from Folkloreatelier/laravel-graphql

### ISSUE THREAD

**Issue by drmax24** [rebing/graphql-laravel#227]
Hi. We are using Folkloreatelier/laravel-graphql extensively in our company. As far as I remember rebing/graphql-laravel was very similar some time ago. That would be nice to replace couple of strings across the project to migrate. Folkloreatelier/laravel-graphql was recently shutdowned. Many people will move. Can you provide some help in advance. Before we start our migration.

Give us some regexps to run across the project may be... Or some advice

**Comment by MrGekko** [comment]
For me it was a drop-in replacement except for a few issues for which i created a pull request and they got merged. Things to look out for:

- Config file has some naming differences
- `middleware_schema` does not exist. Middleware is added to the '[schema](https://github.com/rebing/graphql-laravel#schemas)' itself.
- Not all events are not implemented in this package but I did not use them
- There is a version difference of `webonyx/graphql-php` so my scalar types had to be updated
- Probably lots of stuff I don't use

**Comment by johannesnagl** [comment]
> * Replace `Folklore` for `Rebing` everywhere

this was not working for me - had couple of references that had also slightly changed namespace structures (not only folklore/rebing)

**Comment by whytewolf-ca** [comment]
I recently upgraded from folkloreinc/laravel-graphql to rebing/graphql-laravel and had a couple of items that needed additional work--as noted the configuration middleware for individual schemas has changed, but additionally, the way in which GraphQL enums are created is different, and it looks like the function signature for the resolve method in Query objects is also different (I could be wrong on this however).  Otherwise the migration went smoothly once I found the right version to use with my version of Laravel.

**Comment by mfn** [comment]
FTR I'm working on a guide => https://github.com/rebing/graphql-laravel/pull/364 ; no ETA at this point.

**Comment by mfn** [comment]
I've now added a migration guide coming from Folklore, please check out the readme https://github.com/rebing/graphql-laravel#migrating-from-folklore

If you think anything is missing, please open PRs!
