### ISSUE TITLE
Having problem with Type relationship query

### ISSUE THREAD

**Issue by nomadme** [rebing/graphql-laravel#233]
I looked through the documentation and the issue similar to my issue, but couldn't make it resolve what  I'm getting.

This is in my CategoryType:
```
...
'products' => [
              'type' => Type::listOf(GraphQL::type('product')),
              'query' => function(array $args, $query){
                return $query->where('products.slug', $args['slug']);
              }
            ],
```
Relationship In Category model:
```
public function products(){
        return $this->belongsToMany('App\Models\Namespace\Product', 'lms__product_categories', 'category_id', 'product_id');
    }
```

and this is how I'm querying:
```
category(slug: "foo") {
    name
    slug
    products(slug: "bar") {
      name
      slug
    }
  }
```

This is the error I'm getting:
```
"message": "Unknown argument \"slug\" on field \"products\" of type \"Category\".",
      "extensions": {
        "category": "graphql"
      },
```

**Comment by rebing** [comment]
The `product` Field must have an argument Field `slug`

https://github.com/rebing/graphql-laravel/blob/master/docs/advanced.md#custom-field

**Comment by nomadme** [comment]
Thanks for getting back on this.

I do have a `slug` field in my `product` type like this.

```
class ProductType extends GraphQLType
{
    protected $attributes = [
        'name' => 'Product',
        'description' => 'List of product',
        'model' => Product::class,
    ];

    public function fields()
    {
        return [
            'id' => ['type' => Type::nonNull(Type::string())],
            'name' => ['type' => Type::string()],
            'slug' => ['type' => Type::string()],
            'media' => ['type' => Type::listOf(GraphQL::type('media'))],
            'categories' => ['type' => Type::listOf(GraphQL::type('category')), 'description' => 'Category relations']
        ];
    }
}
```

Do I need to create a `ProductField` class? Like in the doc?

**Comment by rebing** [comment]
Yes, `slug` needs to be an _argument_ not a _field_

**Comment by nomadme** [comment]
Now, how can I return arrays? 

```
class ProductField extends Field
{
    protected $attributes = [
        'description'   => 'A product',
    ];

    public function type()
    {
        return GraphQL::type('product');
    }

    public function args()
    {
        return [
            'id' => ['type' => Type::string()],
            'slug' => ['type' => Type::string()],
        ];
    }

    protected function resolve($root, $args)
    {
        if (isset($args['slug'])) {
            return Product::where('slug', $args['slug'])->first();
        }

        return Product::whereHas('categories', function ($query) use ($root){
            $query->where('slug', $root->slug);
        })->get();
    }
}
```

and my CategoryType:
```
class CategoryType extends GraphQLType
{
    protected $attributes = [
        'name' => 'Category',
        'description' => 'List of product categories',
        'model' => Category::class,
    ];

    public function fields()
    {
        return [
            'id' => ['type' => Type::nonNull(Type::string())],
            'name' => ['type' => Type::string()],
            'slug' => ['type' => Type::string()],
            'description' => ['type' => Type::string()],
            'notes' => ['type' => Type::string()],
            'image' => ['type' => GraphQL::type('media')],
//            'products' => [
//              'type' => Type::listOf(GraphQL::type('product')),
//              'query' => function(array $args, $query){
//                return $query->where('products.slug', $args['slug']);
//              }
//            ],
            'products' => ProductField::class,
            'enabled' => ['type' => Type::boolean()],
            'sort_order' => ['type' => Type::int()],
            'created_at' => ['type' => Type::string()],
            'updated_at' => ['type' => Type::string()],
        ];
    }
}
```

**Comment by mfn** [comment]
Can you be more specific, what is the error you are getting?

----

Also, for `ProductField::resolve` I see an invariance in the code:
- type is defined as `GraphQL::type('product')`
- but you return either a single model with `slug` (because of `->first()`)
  or
- a collection via `Product::whereHas`

This doens't make sense. If the type is `product` you always need to return a product (or null, in your case) but not a specific model or a collection of models.

Also your `ProductField::resolve` doens't make use of the `id` argument, an oversight?

**Comment by nomadme** [comment]
My apologies, that `->first()` was slipped in here from my test run when I try to make sure it was going through without error. But it should be `->get()`.

On the `id` argument, yes, that is just an oversight at the moment.

This is the query I want:
```
query ListCategories2 {
  category(slug: "category-slug") {
    name
    slug
    products(slug: "product-slug") {
      slug
    }
  }
}
```

Yes, that is correct, I want to return as a **collection**. I'm only confused as of the moment, how should I return as an array of product. My `productField class` defined as `a product`, but In my category I want the products returned as a an array.

I used to have a 
```
'products' => [
       'type' => Type::listOf(GraphQL::type('product')),
       ...
]
```
I hope this makes sense. Thanks.

**Comment by mfn** [comment]
What you describe (last code fragment) looks current, that's why I asked: Can you be more specific, what is the error you are getting?

**Comment by nomadme** [comment]
Well, I don't get any error but null. 

To be more specific, how can I make it return collection/array? that is all I want.

**Comment by mfn** [comment]
`null` is weird. It seems to me then that your relation is not loaded at all (because an non-existent relation still returns a "collection" which means it's still an "array of things", but it's empty => not your case, though).

You have to debug, is your `query` definition executed? Can you replace with with a `resolve` and return the collection directly?

I _think_ that maybe some assumption is going wrong and it tries to access your Laravel model `$category->products` which does not exist (and it's not necessary to be there, if you use your own resolver). Try that.

**Comment by nomadme** [comment]
I'm getting the correct data when I debug.

![Screenshot 2019-03-20 21 11 26](https://user-images.githubusercontent.com/6267271/54730069-beaf3400-4b54-11e9-9a46-f4417c705312.png)

![Screenshot 2019-03-20 21 10 10](https://user-images.githubusercontent.com/6267271/54730034-9293b300-4b54-11e9-9f48-022f86b32b46.png)


But here I'm expecting an array to be returned in the `products`, but getting `null`

![Screenshot 2019-03-20 21 08 32](https://user-images.githubusercontent.com/6267271/54730077-c969c900-4b54-11e9-9238-ff2af650ece5.png)

**Comment by nomadme** [comment]
I updated my field type as an `listOf` and it worked as expected. Somehow, I missed or simply confused on this `type`.

In my `ProductField` class:
```
...
public function type()
    {
        return Type::listOf(GraphQL::type('product'));
    }
...
```

Thanks for your help troubleshooting this with me.

**Comment by mfn** [comment]
Glad you could solve it.

As a "general rule of thumb" though, it's a better practice to actually mark everything as `Type::nonNull()` by default.

In 90% of the cases your data usually _is there_.

Important: this also includes types **in** lists, e.g. instead of
```php
Type::listOf(GraphQL::type('product'));
```
it's better have
```php
Type::nonNull(Type::listOf(Type::nonNull(GraphQL::type('product'))));
```
Especially the inner `null` is important to consider, because you can ask the question yourself: when I'm returning a collection of `product`, why would any of them be `null`?

For collection it really doesn't make sense and having this stricter definition allows you earlier catch this errors (your GraphQL query will fail if there would ever be a null element).

Note: this is _rule of thumb_, but in practice a very good one.

It also tells the consumers of your API what do expect and they do not have to work with so many "ah, ok, this field can be null, have to also consider this"-cases.

**Comment by nomadme** [comment]
Appreciate ya!

I like that idea and will implement it from now on.
