### ISSUE TITLE
Help! How to rename field in query?

### ISSUE THREAD

**Issue by MrJmpl3** [rebing/graphql-laravel#31]
I need rename field in query and in backend rename to field 

Same Laravel Fractal

Example:
My table users: Columns: Id, Name , Email

Request:
query Users { users{ code nick contact} }

I dont need exposed the field from my database ..

Any ideas?

**Comment by rebing** [comment]
Use a magic attribute `getCodeAttribute()` in the UserModel (or `resolve` in GraphQL Type) and then `selectable => false` in the Type. https://github.com/rebing/graphql-laravel#creating-a-query

**Comment by nyalex** [comment]
@rebing I am also stuck on this. Could you elaborate on how to do this? Your solutions seem to be hacks, unfortunately. Perhaps it's a good idea to add a "name" key in the `fields()` method in the type file?

**Comment by rebing** [comment]
There _is_ a 'name' attribute in fields() type

**Comment by mebranemlm** [comment]
Hi. Is there a way to use `$field->getSelect()` together with aliases? I mean when I use "name"  attribute in fields() type it returns the value with the alias attribute (for example `'nick'=> 'Jon Doe'` instead of `'name'=> 'Jon Doe'`, using MrJmpl3 example) and that's ok, but when I want to use $field->getSelects() in Query and 'selectable'=>true in Type, it returns `'users.nick'` instead of `'users.name'`.  And if I use 'selectable' => false it simply doesn't return the field.

Same thing with $args in Query and Mutation. When I use name attribute in args() function (for example: `'email' => ['name'=>'contact']`), resolve() function receives `[contact=>"jondoe@gmail.com"] `instead of `[email=>"jondoe@gmail.com"]`. And if I use 'contact'=>['name'=>'email'] the interface requires email instead of contact. The idea is that when I send alias attributes from interface, in resolve() I want to get the original attributes. 

I'm using foreach to iterate in Type fields to transform $args and select aliases to original attributes, but it complicates too much when I want to create iterate functions for where, sort, etc. Maybe is there a better way to do this?

**Comment by rebing** [comment]
Hi, I'm not really familiar with the `name` attribute and how it _should_ work. You can maybe look into it and create a PR, if you find the problem.

PS. `'selectable' => false` is working correctly and `getSelect()` should NOT return the field in that case.
