### ISSUE TITLE
Schema name can't contain hyphens

### ISSUE THREAD

**Issue by AlexanderSix** [rebing/graphql-laravel#465]
### Versions:
- graphql-laravel Version: 2.0.1
- Laravel/Lumen Version: 5.8.33
- PHP Version: 7.2.21

### Description:

At work, we recently added this package to a project that we have started for a client (and we're loving the package, by the way), but we bumped into some problems when trying to create a second schema to read from. We were getting a `NotFoundHttpException` each time we tried to access the schema via the api.

Our first schema was called "read", but the one that was giving us problems was called "read-public".

After some trial-and-error, we found out that replacing the hyphen (-) with an underscore (_) fixed the problem. That said, is this a bug, or is this intended functionality? If it **is** how the package is supposed to work, maybe we should add something to the "Schema" section of the documentation that explicitly says this.

If you want to go the route of adding to the documentation, I would be happy to add that in a PR when I have a spare few minutes over the next few days.

### Steps To Reproduce:

1. Add a schema to the 'schemas' array in graphql.php that has a hyphen(-) in the name
2. Remove any middlewares that are attached to the query
3. Try to hit that endpoint with an API request
4. You should receive a `NotFoundHttpException` on the response

**Comment by mfn** [comment]
Indeed, https://github.com/rebing/graphql-laravel/pull/467 shows it doesn't work.

No idea why and, yes, my expectation would be that it should work 🤷‍♀️

**Comment by mfn** [comment]
Can you help debugging this?

**Comment by mfn** [comment]
It seems the `->where()` calls sprinkled all over `src/routes.php` cause this. When I comment them out, the test from the other PR works (or fails, however you view it: the exception is not thrown anymore).

**Comment by mfn** [comment]
Correct, in terms of regex, they do.

I've never used the `->where()` feature myself, literally no idea why it's used here.

Seems there's also no test for it, I can remove them all and the whole suite passes (except the new test specifically for this scenario: because it would fail because it "works").

(I also wonder how they work when they've no delimiter anywhere 🤔 but I see it gets passed to the symfony route class, so 🤷‍♀️)

This is the commit introducing the feature: https://github.com/rebing/graphql-laravel/commit/c44666b7746213851fc2290313618cf1c18f2a52

The commit message does not give much away, also no references to anything.

The added `{` and `}` turns the previous literal part into a route parameter. Then it seems the `->where()` is used to define matching rules for the parameter which is ... literally the same name, again.

Would appreciate help from someone more knowledgeable in this area 🤷‍♀️
