### ISSUE TITLE
Consider including thrown Exception in the response 

### ISSUE THREAD

**Issue by paulomunky1** [rebing/graphql-laravel#493]
It would be useful for testing purposes to have access to any thrown exceptions in the GraphQL response. For example:

If my code throws a permissions exception, I want to be able to test for this in my phpunit tests. With the current Graph QL response I can't see how to explicitly test for this exception being thrown

**Comment by mfn** [comment]
Did you try enabling `app.debug`? If you're using the default `\Rebing\GraphQL\GraphQL::formatError` you will get a `debugMessag` and also a `trace` property (this is actually supported by webonxy directly; it's just implicitly triggered when `app.debug` is disabled).

If you're not satisfied with the specifics, you can always use your own config `graphql.error_formatter` and add more details.

When _testing for_ error responses in tests, I prefer not to have the e.g. `trace` being exposed because I prefer to check the whole response. In such cases I use a method like this to de-noise the debug output:
```php
    private function removeErrorsNoise(array $json): array
    {
        if (!isset($json['errors'])) {
            return $json;
        }

        foreach ($json['errors'] as &$error) {
            unset($error['locations'], $error['extensions']['category'], $error['path'], $error['trace']);

            if (empty($error['extensions'])) {
                unset($error['extensions']);
            }

            if (isset($error['debugMessage']) && $error['debugMessage'] === $error['message']) {
                // Trace and debugMessages come together; if we remove one,
                // we assume it's fine to remove the other too
                unset($error['debugMessage']);
            }

            // Make error more clean for tests in case of validations
            if ($error['message'] === 'validation') {
                unset($error['debugMessage']);
            }
        }
        unset($error);

        return $json;
    }
```

You can also look into `\Rebing\GraphQL\Tests\TestCase::graphql` and `\Rebing\GraphQL\Tests\TestCase::httpGraphql` for some inspiration how to improve DX in certain cases.

**Comment by paulomunky1** [comment]
This is super handy thankyou Markus, perfect explanation and advice

I really appreciate you taking the time to reply to me, you've created an
amazing package and I've given it a star on Github!

Regards,
Paul King
07957570853

**Comment by mfn** [comment]
Thanks for the kind words!

But: I didn't create the package, I just happen to be most active developer at the moment ;)
