### ISSUE TITLE
Support for Apollo Tracing

### ISSUE THREAD

**Issue by georgeboot** [rebing/graphql-laravel#499]
### Summary

It would be great if this package could support [Apollo Tracing](https://github.com/apollographql/apollo-tracing).

This would allow super easy (automated) field-level performance measurements.

**Comment by mfn** [comment]
Sounds useful, I think lighthouse also has this if I'm not mistaken: https://github.com/nuwave/lighthouse/tree/master/src/Tracing

**Comment by georgeboot** [comment]
Yes that is true indeed.

We are currently using Lighthouse but it just has too much magic for me. It works super good for simple use cases, but as soon as you want something different, you need to hack a lot around. That is how I ended up here. Might as well write all the logic in PHP and have full control.

Our API is proxied through an Apollo Server that captures and strips the tracing section and reports it to the Apollo Platform.

**Comment by mfn** [comment]
I'm not sure having an open issue and no one working on it is useful.

Features are usually implemented "need driven" and as long as no one comes around with the "need" to implement, no matter we've this issue or not, it probably won't get implemented.

I vote for closing this as it doesn't reflect whether this features gets ever done or not.

**Comment by georgeboot** [comment]
Or doesn’t have the competence. But I see your point.

I would say this is still a nice have and all it’s doing is increment the open issue count by one.

**Comment by mfn** [comment]
> Or doesn’t have the competence. But I see your point.

Neither have I 😄 

Since there's no signal here for working on it, as mentioned I'm closing it.

My philosophy, and also experience, is that I don't see value on lingering open issues which have no inherent traction and are not about bugs.

Projects gets PRs when people are motivated to do so and I'm not inherently seeing a direct relation to open issues. I saw people open issues and creating PRs to fix them but I also saw people coming up with PRs having no issue and just implement what they need/want.

I'm sure if the next dev comes around and needs the tracing support and has the skills, they don't need an issue to implement it.

Status: closing issue, welcoming PRs 😄
