### ISSUE TITLE
Trim mutation arguments like laravel TrimStrings middleware

### ISSUE THREAD

**Issue by tpetry** [rebing/graphql-laravel#505]
Currently it is problematic to apply validation rules to the input of mutations: For Laravel http requests all spaces at the beginning and end of input values are removed using the `TrimStrings` middleware. So Validation Rules like `between:10,50` can work on the real length without whitespaces.

However, this is not possible with GraphQL queries so far. The validations work directly on the data from the query and thus on strings with spaces. And there is no way to change it or hook into it to change the behaviour.

It would be very nice if there was an option to apply the trimming of whitespaces recursively to the arguments of GraphQL queries.

**Comment by mfn** [comment]
Hmm, there was another issue a few months ago => https://github.com/rebing/graphql-laravel/issues/248

It's true the library doesn't provide anything out of the box. The "graphql way" would be to use directives, which aren't supported though.

But I think there could be an easy workaround with your own middlware:
```php
    public function handle(Request $request, Closure $next)
    {
        $input = $request->input();
        // trim…
        $request->merge($input);

        return $next($request);
    }
```
For this to work, you would not pass the data as `variables` from the client though, not within the query. Then you can recursively trim it.

**Comment by tpetry** [comment]
> For this to work, you would not pass the data as variables from the client though, not within the query. Then you can recursively trim it.
Yeah and that's the problem. This approach may work if you are the only one using the api. But if it's an public api you can't enforce this rules.

I thought maybe a small snippet somewhere could be implemented to trim the values before they are used for everything.

**Comment by mfn** [comment]
Certainly, but I prefer there to be used an "official channel" to accomplish this instead of wiping up something custom.

**Comment by tpetry** [comment]
What do you mean by official? Facebook only publishes the graphql spec and reference implementation which webonyx ported to php. Logic like trimming whitespaces has done by an upper layer (like laravel implementing ontop of basic php http request).
So imho your library is the correct place to implement this functionality in the layers.

**Comment by mfn** [comment]
Apologies for being unclear. Basically what I said in https://github.com/rebing/graphql-laravel/issues/505#issuecomment-546481586 but more elaborate:

Yes, I think implementing this as part of the library is the appropriate. That's why I also didn't close this issue.

With "official" I meant: I don't want to introduce some artificial trim layer "because reasons".

Within the GraphQL spec, there's a clear candidate for implementing this: [directives](https://graphql.github.io/graphql-spec/June2018/#sec-Language.Directives).

But this library doesn't support them (though the underlying webonxy does).

Point in case: [lighthouse supports directives and even implements a trim directive](https://lighthouse-php.com/4.5/api-reference/directives.html#trim), AFAICS exactly working the way we would need it here.

A quick workaround would be a) use GraphQL variables and b) add a custom middleware doing this.

The gist is: I think the only right/correct way to do is, is to implement generic support for directives => that is what I meant with "official". Instead of coming up with a library specific solution.

Hope that clears up the confusion; again sorry for being unclear.

**Comment by crissi** [comment]
weird, this should be working, I have been using the ConvertEmptyStringsToNull middleware which is similar to the one you mentioning and that one is applied.

**Comment by tpetry** [comment]
@crissi The `ConvertEmptyStringsToNull` middleware will ensure a string like ` `  can't pass the `required` validation. But without trim support a string like `a   ` will pass a `min:5` rule because whitespaces are not removed
