### ISSUE TITLE
Allow manual adding to $getSelectFields

### ISSUE THREAD

**Issue by georgeboot** [rebing/graphql-laravel#510]
## Summary
It would be very powerful if developers can manually add fields, relations and counts to the `$getSelectFields`.

### Background
Imagine the following types:
```gql
type Event {
    id: ID!
    name: String
    tickets: [Ticket]
}

type Ticket {
    id: ID!
    event: Event!
    date: Date
    name: String
    price: Int
}
```

As you can see, we have an event with multiple tickets. Each ticket has a date. These dates don't have to be unique.

Lets imagine we have the following tickets:

| Name  | Date | Tickets Available |
| ------------- | ------------- | --: |
| Day 1 Regular  | 2020-01-01 | 100 |
| Day 1 VIP  | 2020-01-01 | 10 |
| Day 2 Regular  | 2020-02-01 | 100 |
| Day 2 VIP  | 2020-01-02 | 10 |
| Day 3 Regular  | 2020-03-01 | 100 |
| Day 3 VIP  | 2020-01-03 | 10 |

Now, from the event I want to have a list of available dates.

```gql
type EventDay {
    date: Date
    ticketsAvailable: Int
}
type Event {
    id: ID!
    name: String
    tickets: [Ticket]
    dates: [EventDay]
}
```

The expected output:
```json5
{
  "data": {
    "event": {
      "id": "1",
      "dates":[
        {
          "date": "2020-01-01",
          "ticketsAvailalbe": 20 // we already have 90 total sales for this date
        },
        {
          "date": "2020-01-01",
          "ticketsAvailalbe": 100 // total of 10 sales
        },
        {
          "date": "2020-01-01",
          "ticketsAvailalbe": 110 // no sales yet
        }
      ]
    }
  }
}
```

### The problem
I've added a `getDatesAttribute` method to my `Event` model. In there, I select all tickets, filter out some unwanted statuses, and for every ticket, we get the sales count (the `Tickets Available` from the example table is calculated from our `sales` table) et cetera.

There is unfortunately no way (that I know) to tell the `Event` resolver to eager load some things so that the `getDatesAttribute` will not create a `n+1` issue.

### My idea
It would be very powerful if I could specify what fields to eager load in my `App\GraphQL\Types\EventDay`.

Also, the `$getSelectFields` currently only supports fields and relations, not counts. I would also love to see that one added.

With these improvements, my `EventDay` type will inform my `Event` type that it would love to eager load things like `$event->loadCount('tickets.sales')` etc.

**Comment by crissi** [comment]
for use cases like this you can use, http://webonyx.github.io/graphql-php/data-fetching, see "Solving N+1 Problem"

**Comment by mfn** [comment]
I too have no idea how we could realistically expand `SelectFields`

I don't want to piss on anyone parade, but the current code is quite a mess there. But maybe that's also because what it tries to solve isn't really easy, either.

I also question the approach to generate upfront query conditions by introspecting the tree.

Also for almost anything, how `SelectFields` works is quite independent of the actual GraphQL implementation. AFAICS it only requires the proper configuration as part of the type definition but nothing else. The biggest dependency is the AST from the `ResolveInfo` which is actually from the underlying webonxy library.

Thinking out loud: I could imagine `SelectFields` could be a decoupled standalone component from this library.

data fetching / data loaders using deferred / promises is IMHO the correct way to do but there may be reasons not to do it.

Ideally this library would not endorse any specific aspect and be just independent of this decision and simply refer to outside libraries for these tasks.

**Comment by crissi** [comment]
https://github.com/rebing/graphql-laravel#type-relationship-query may also help your case, you can add anything to the query here

**Comment by georgeboot** [comment]
I have now fixed this by adding an `EventBuffer`:

```php
<?php

declare(strict_types=1);

namespace App\Models\Buffers;

use Illuminate\Database\Eloquent\Collection;
use App\Models\Event as EventModel;
use Illuminate\Support\Arr;

class Event
{
    /**
     * @var Collection[]
     */
    protected static $map = [];

    protected static $loaded = false;

    public static function buffer(EventModel $event, string ...$loaders): void
    {
        foreach ($loaders as $loader) {
            if (!isset(self::$map[$loader])) {
                self::$map[$loader] = new Collection;
            }

            self::$map[$loader]->put($event->id, $event);
        }
    }

    public static function getDates(EventModel $event): array
    {
        $model = Arr::get(self::$map, "dates.{$event->id}");
        
        return $model->dates;
    }

    // other getters

    public static function load(): void
    {
        // make sure we only process the buffer once
        if (self::$loaded) {
            return;
        }

        foreach (self::$map as $loader => $models) {

            switch ($loader) {
                case 'dates':
                    self::loadDates($models);
                    break;
                
                // other loaders
            }
        }

        self::$loaded = true;
    }

    protected static function loadDates(Collection $models): void
    {
        $models->load([
            'ticketTypes' => function($query) {
                $query->withCount('tickets');
            },
            'ticketTypes.event',
        ]);
    }

    // other loaders
}
```

And in my Event type:
```php
<?php

declare(strict_types=1);

namespace App\GraphQL\Types;

class Event extends GraphQLType
{
    protected function resolveDatesField(EventModel $root, array $args): Deferred
    {
        EventBuffer::buffer($root, 'dates');

        return new Deferred(function () use ($root) {
            EventBuffer::load();

            return EventBuffer::getDates($root);
        });
    }
}
```

**Comment by crissi** [comment]
Other ways this might be redobles sepensing on our query is the **always** option ir an alias with a Call back returning An subselect statement

**Comment by mfn** [comment]
Seems to me the issue is solved, using dataloaders IMHO is also the preferred way and I use it a lot for such cases instead of frankensteining SelectFields

**Comment by Artem-Schander** [comment]
Sorry to disturb the peace in this closed issue. I'm not sure if i should open a new one (maybe even at webonyx/graphql-php).

However, some time ago I struggled with N+1 and could not solve it with SelectFields, so I found this issue and wrote buffers. It seemed to solve the issue just fine.
Today I accidentally discovered that in some cases this solution does not work.

Lets say I have the following relations:
<img width="511" alt="Bildschirmfoto 2023-07-06 um 17 37 24" src="https://github.com/rebing/graphql-laravel/assets/1243826/ad4a0c75-4963-4352-bc40-436406e0641c">

Every entity has its own Buffer and the resolvers are implemented just like shown above.
When I ask the following, I'll get the beloved N+1 issue for everything beneath Image.
```gql
query FetchAuthors {
    Authors {
        id
        images {
            id
            files {
                id
            }
        }
        books {
            id
            images {
                id
                files {
                    id
                }
            }
        }
    }
}
```

But If I ask only for author-books or only for author-images then no N+1 issue occurs.

It would be really nice if someone could share with me some knowledge. I can not see what the issue here is and I don't feel like firing up xdebug and dive into the `Deferred` execution.

**Comment by Artem-Schander** [comment]
@mfn 
Thanks for the quick response. I dug a bit and found out that the processing order is not like i understood/expected it.
It seems that `Deferred` resolves the requested data for every node sequentially (even before the next data gets batched/loaded). I thought it would act at the very end of processing the whole request.

So this would be the resolving order of my example:

1. batch `author->images`
2. load `author->images` (set `loaded` flag)
3. `Deferred` resolve `author->images`
4. ...
5. batch `author->books->images`
6. end

Load `author->books->images` is not getting called (most likely because the `loaded` flag is already set).
So your assumption (case 2) seems to be correct.

I have tried the "naive approach" before getting into ID-tracking, but resetting the loaded flag does not help at all.
I'm aware that this wouldn't be a proper solution anyway, I'm just trying to narrow the cause down since I do not fully understand what the root for this issue is.
