### ISSUE TITLE
Login success/fail implementation

### ISSUE THREAD

**Issue by mwagena** [rebing/graphql-laravel#522]
### Versions:
- graphql-laravel Version: 2
- Laravel Version: 6
- PHP Version: 7

### Question:
Hi,

What's the best method to implement login failures in a mutation?
I couldn't find a solution in the readme file.

Thanks in advance.

Martijn

**Comment by georgeboot** [comment]
What do you mean exactly? Are you trying to perform a login (using username/password) using a mutation and want to handle cases like a wrong password?

Or are you referring to login as in, supply an access token, and want to handle cases where that access token is invalid?

**Comment by mwagena** [comment]
hi @georgeboot 
I'm talking about performing a login with username and password and handle the case with a wrong password.
How do you guys implement cases like this?

**Comment by georgeboot** [comment]
It's indeed a bit different than you would have with a traditional REST api with HTTP status codes etc.

You basically have 2 options.

1. Return null instead of the normale response (access token etc)
2. Return an error. This could be a validation error (technically true) or some other error.

There is no real good way in my experience. More the less because most people use oAuth and have their auth logic on a regular REST api, and thus don't have the solve this issue.

**Comment by mwagena** [comment]
I see, currently I solved it with the following pieces of code.
I'm curious about your idea about this:

```php
use GraphQL\Error\Error;
```
```php
public function type(): Type
{
    return Type::boolean();
}
```
```php
if (!$contact) {
    throw new Error('Contact not found');
}
```
```php
return $contact->delete();
```

**Comment by georgeboot** [comment]
Yeah that looks good.

Personally I would adjust the return type to something else. Currently, it will return `true` on success, and error on failure. It will never return `false`, so why return a boolean? Rather return the user or so.

**Comment by mfn** [comment]
Issue seems solved to me.

Also IMHO the library shouldn't endorse any specifics in this regard, it's often application specific.
