### ISSUE TITLE
how to use $context argument of resolve method

### ISSUE THREAD

**Issue by apapilov-sc** [rebing/graphql-laravel#583]
that is how apollo graphql server describes what for context arg is needed. Is that possible to use this argument for similar purposes in rabing-graphql server??

> context: This is an object shared by all resolvers in a particular query, and is used to contain per-request state, including authentication information, dataloader instances, and anything else that should be taken into account when resolving the query. If you're using Apollo Server, read about how to set the context in the setup documentation.

**Comment by mfn** [comment]
Yes, the philosophy is the same. It's a shared value between all resolvers of a GraphQL request.

By default it's just the authenticated user (see `\Rebing\GraphQL\GraphQLController::queryContext`), but you can override and return anything you want (i.e. a dedicated context object which holds, besides the auth user, your data loaders and whatever you want to keep there).

It kinda serves as a cached/shared instance during the request, so be considerate what data you put into it ("caching effect"), otherwise embrace where you need it!
