### ISSUE TITLE
how can I get root's query arguments in child filed resolver?

### ISSUE THREAD

**Issue by apapilov-sc** [rebing/graphql-laravel#587]
how can I get root's query arguments in child filed resolver?

**Comment by mfn** [comment]
A child resolver only receives the direct arguments because there's no relation between a field resolver  and the query it might be part of.

I think the workaround is to:
- use a custom graphql context
- set the root arguments there in query resolver
- them out in the child field

See https://github.com/rebing/graphql-laravel#resolve-method regarding customization.

**Comment by crissi** [comment]
You should be getting the Resolveinfo as the third param in the resolver, 

So I think you can do this:
$resolveInfoFieldsAndArguments = new ResolveInfoFieldsAndArguments($resolveInfo);

 $resolveInfoFieldsAndArguments->getFieldsAndArgumentsSelection($depth),

**Comment by mfn** [comment]
> You should be getting the Resolveinfo as the third param in the resolver,

🤔

Ok, maybe I got it wrong, but AFAIK the ResolveInfo also does not allow you to "walk up the tree", i.e. can't access parent nodes and thus can't access the arguments either … but maybe I'm wrong 🤷‍♀️
