### ISSUE TITLE
How get $appends attribute in a submodel

### ISSUE THREAD

**Issue by dilakv** [rebing/graphql-laravel#601]
### Versions:
- graphql-laravel Version: ^4.0
- Laravel Version: ^6.2
- PHP Version: 7.4.0

i tried to use "appends" in models, i did define an attribute in a submodel, but this return an error from SQL.

Suppose the next models:

```
student
  - id
  - name

carreers
  - id
  - name
  - student_id
  - modality_id
  - modality (*append modality name)

modality
  - id
  - name
```

if i make an:

```
carrers{
    name
    modality
}
```

It works, I get a good response, with all the data i need, 

But when i use the query:

```
student{
     name
     carreer{
         name
         modality
     }
}
```

It fails

And it doesn't matter in which scenario i applied this, if i want an append attribute defined in a submodel  i always get something like:

`Column not found: 1054 Unknown column 'carrers.modality' in 'field list' `

**Comment by mfn** [comment]
Hmm, using $appends should have not relation to that kind of bug. To the best of my knowledge $appends isn't even used in anyway; this Laravel feature appends attributes when a model is serialized, which isn't how this library operates (attributes are directly accessed due to the default resolver).

Does it really "work" when you remove $appends?

TBH, I've a vague idea about the general relations, but the devils likely in the details.

It would be great if you could past all the models relations, resolvers used, etc.
Or simply put up an example project on github using eg. sqlite and instruction how to "break" it.

**Comment by mfn** [comment]
Closing due to lack of feedback; feel free add new information when available and we can reopen the issue!
