### ISSUE TITLE
Is there any built-in support for Federation?

### ISSUE THREAD

**Issue by jamilnyc** [rebing/graphql-laravel#678]
### Versions:
- graphql-laravel Version: 5.1.4
- Laravel Version: 6.18
- PHP Version: 7.3

### Question:

Is there any support or option for **Federation** in this library? I didn't notice anything mentioned in the docs, or the config file. I am building a GraphQL service that will be integrated with other GraphQL services managed by an [Apollo Federation](https://www.apollographql.com/docs/apollo-server/federation/introduction/) service (these other GraphQL services and Apollo are not managed by me).

I am trying to integrate something like this repo here: https://github.com/pascaldevink/php-graphql-federation. 
However, to do so would require modifying the function `Rebing\GraphQL\GraphQL::queryAndReturnResult()`. While I could do this with a `composer` patch file, I would like to avoid it if possible.

Specifically the change I would have to make is something like:

```php
public function queryAndReturnResult(string $query, ?array $params = [], array $opts = []): ExecutionResult
{
    $context = $opts['context'] ?? null;
    $schemaName = $opts['schema'] ?? null;
    $operationName = $opts['operationName'] ?? null;
    $rootValue = $opts['rootValue'] ?? null;

    $schema = $this->schema($schemaName);

    $errorFormatter = config('graphql.error_formatter', [static::class, 'formatError']);
    $errorsHandler = config('graphql.errors_handler', [static::class, 'handleErrors']);
    $defaultFieldResolver = config('graphql.defaultFieldResolver', null);

    // These 3 lines were added by me.
    $federation = new \PascalDeVink\GraphQLFederation\Federation();
    $schema = $federation->extendSchema($schema);
    $rootValue = $federation->addResolversToRootValue($rootValue ?? []);

    $result = GraphQLBase::executeQuery($schema, $query, $rootValue, $context, $params, $operationName, $defaultFieldResolver)
        ->setErrorsHandler($errorsHandler)
        ->setErrorFormatter($errorFormatter);

    return $result;
}
```

If anyone has any experience dealing with Federation with this library, I'd really appreciate any thoughts you might have.

**Comment by mfn** [comment]
Not using federation so can't help there.

But: improving the code to allow this kind of changes without composer hack is certainly possible.

We just need to be careful regarding potential backward compatible breaking changes

I also worked a bit on https://github.com/rebing/graphql-laravel/pull/668 which, whilst not yet, may also result in changes in this method too.

**Comment by mfn** [comment]
Given your example, I see that in order to achieve your federation integration, you need to be able to mutate `$schema` and `$rootValue`.

> While I could do this with a `composer` patch file, I would like to avoid it if possible.

I think the proper solution is to:
- extend `\Rebing\GraphQL\GraphQL` and register your own service as `'graphql'`
- override `\Rebing\GraphQL\GraphQL::queryAndReturnResult`
- and thus incorporate your own logic

No composer-patching needed.

I'm not sure built-in support (i.e. adding yet another dependency on another package) is warranted currently. I'm not saying there's no need, but the example you provided would force federation integration on everyone using this library.

I'm closing this as I feel what is needed to achieve the goal itself is possible already today although no built-in support is provided.
