### ISSUE TITLE
Why not wrap webonyx standard server ?

### ISSUE THREAD

**Issue by illambo** [rebing/graphql-laravel#702]
### Versions:
- graphql-laravel Version: 6.1.0
- PHP Version: 7.x

### Question:
Does anyone know why this package doesn't wrap the [webonyx standard server](https://webonyx.github.io/graphql-php/executing-queries/#using-server) ?
I think this makes some topics redundant to address and complex to integrate.

Thanks

**Comment by mfn** [comment]
I can only spear for myself, basically "joining" this project at some point last year.

I've never used the standard server 😄 TBH I don't even know what/how it exactly works/does. I _thought_ it was a dev only example and not something for "production", but I just never bothered thinking about it.

Also when I joined this project, before that it was a fork/code sharing (don't know the details) with https://github.com/folkloreinc/laravel-graphql which eventually shut down and they both seem to have the same/similar origins and thus it came about it's not being there. Maybe the server was not there when it began etc.

Since I don't even know what it is exactly doing, what advantages does it have? What parts would it replace? Supposedly it needs some adapter then for integrating into Laravel? This project uses lots of custom "graphql type config keys", are they still supported?

**Comment by illambo** [comment]
It was just to understand for a moment, because I was reading from [docs](https://webonyx.github.io/graphql-php/executing-queries/#using-server) I read:

> Server also supports PSR-7 request/response interfaces [...]
>
> [...]
>
> PSR-7 is useful when you want to integrate the server into existing framework:
> - PSR-7 for Laravel
> - Symfony PSR-7 Bridge
> - Slim
> - Zend Expressive

Unfortunately I don't even know this package and its limitations.

**Comment by illambo** [comment]
I asked for some clarification in webonyx/graphql-php#753, just to understand the purpose.

**Comment by illambo** [comment]
I close the question as I had an overview about it. 
Thanks
