### ISSUE TITLE
Cannot query field \"products\" on type \"Query\". Did you mean \"product\"?

### ISSUE THREAD

**Issue by meylisday** [rebing/graphql-laravel#730]
### Versions:
- graphql-laravel Version: 1.5.4
- Laravel Version: 8.12
- PHP Version: 7.4

### Question:
I have the same issue as [#276](https://github.com/rebing/graphql-laravel/issues/276)
My question in [stackoverflow](https://stackoverflow.com/questions/66869378/graphql-returns-the-error-message-cannot-query-field-when-i-try-to-get-all.). If you don't mind I will not duplicate screenshots and code. Thanks.

**Comment by mfn** [comment]
> graphql-laravel Version: 1.5.4

There's no such version, but I guess you just mixed it up and it's the one of stackoverflow. Either way: it's quite outdated!

This error usually means that the query has not been properly registered, i.e GraphQL "can't find it".

Seeing though that all the code you pasted looks correct on first sight, I'm wonder if you may have cached the config unintentionally?

Since changing the schema effectively means changing the config, this could explain it. Please try deleting the config cache via `./artisan config:clear`.

**Comment by mfn** [comment]
Closing due to lack of feedback; happy to re-open if more info is provided.
