### ISSUE TITLE
Almost esoteric issue with Exception Handler

### ISSUE THREAD

**Issue by nicogranelli** [rebing/graphql-laravel#749]
### Versions:
- graphql-laravel Version: 7.0.1
- Laravel Version: 8.36.2
- PHP Version: 7.4

### Description:

The problem is that Graphql errors skip the exception handler defined in my project. I think is "almost esoteric" because even if I found a fix, I can't explain why it works. 

if you replace the line here:
https://github.com/rebing/graphql-laravel/blob/master/src/GraphQL.php#L475

With just 
```
report($error);
```
It works as expected. 

So, the idea is that using the helper is somewhat better than doing what the code does, even if the code uses a more correct way of doing... the magic of laravel I guess.

I wanted to create a PR and all that, but I don't feel comfortable, as I can't explain it, nor found a way to reproduce it on a test in my project. 

How should I proceed?

**Comment by mfn** [comment]
`report($error);` is quite a small function:
```php
    function report($exception)
    {
        if (is_string($exception)) {
            $exception = new Exception($exception);
        }

        app(ExceptionHandler::class)->report($exception);
    }
```
Assuming in `handleErrors` (the method you reference the line in) is never receiving strings (because it's always some Exception or Error object), it comes down to just
```php
app(ExceptionHandler::class)->report($exception);
```
which is exactly what this method does:
- get the exception handler: https://github.com/rebing/graphql-laravel/blob/da800316df4e3ca44aa1f12ec963c258baad54b6/src/GraphQL.php#L451
- report it: https://github.com/rebing/graphql-laravel/blob/da800316df4e3ca44aa1f12ec963c258baad54b6/src/GraphQL.php#L475

(There's no practical difference between `app(ExceptionHandler::class)` and `app()->make(ExceptionHandler::class)` IMHO)

The one difference I can see between the two approaches: calling `report()` will resolve the exception handler every time, not just once. If that makes a difference.. well, you can test it by transforming the method into the following and see if it also fixes it for you or now:
```php
    public static function handleErrors(array $errors, callable $formatter): array
    {
        foreach ($errors as $error) {
            // Try to unwrap exception
            $error = $error->getPrevious() ?: $error;

            // Don't report certain GraphQL errors
            if ($error instanceof ValidationError ||
                $error instanceof AuthorizationError ||
                !(
                    $error instanceof Exception ||
                    $error instanceof PhpError
                )) {
                continue;
            }

            if (!$error instanceof Exception) {
                $error = new Exception(
                    $error->getMessage(),
                    $error->getCode(),
                    $error
                );
            }

            $handler = app()->make(ExceptionHandler::class);
            $handler->report($error);
        }

        return array_map($formatter, $errors);
    }

```

> I wanted to create a PR and all that

First I suggest we dig more into this; unless it's clear what's going on, there's no point in making PRs.

The way I see it, you've two options:
- fire up your favourite debugger and see what's going on
- override the `errors_handler` in the configuration (See https://github.com/rebing/graphql-laravel#configuration-options , I just added the docs to make the config more discoverable)
  > Custom Error Handling. The default handler will pass exceptions to laravel Error Handling mechanism
  
  I.e. you can fully replace the above `handleErrors` methods if it doesn't suit your needs.

**Comment by mfn** [comment]
Closing due to lack of feedback; happy to re-open if more info is provided.

**Comment by nicogranelli** [comment]
I forgot to mention something: I found this when I was trying to understand why GraphQL Exceptions weren't getting reported to sentry. At the end I solved it with a custom handler that uses "report". 

I see 2 options to close this: 
1) changing the code to use report
2) adding a warning in the docs. 

A simpler third one would be to change the title of this issue to make it more clear. So google index it and if someone have the same problem in the future, can read a way to fix it.

**Comment by mfn** [comment]
I'm not changing core or adding a warning unless we understand what the underlying problem is; so far I don't see any of this 🤷‍♀️

**Comment by mfn** [comment]
Re-opening in case you want to come back with more details!

I think a good start would be a repo reproducing the issue.

**Comment by mfn** [comment]
Closing due to lack of feedback; happy to re-open if more info is provided.
