### ISSUE TITLE
404 after updating to 8.0.0-rc4

### ISSUE THREAD

**Issue by Artem-Schander** [rebing/graphql-laravel#813]
### Versions:
- graphql-laravel Version: 8.0.0-rc4
- Laravel Version: 7.30.4
- PHP Version: 7.4

### Description:

I'm sorry if I missed some breaking changes, but after updating from rc3 to rc4 I'm getting 404 on all of my graphql routes.
`php artisan route:list` says the routes are still there.
<img width="1257" alt="Bildschirmfoto 2021-08-13 um 22 33 10" src="https://user-images.githubusercontent.com/1243826/129415593-7d47cfc0-ff64-4b9c-a463-926eb269f825.png">

I have multiple schemas.. maybe it is relevant
<img width="639" alt="Bildschirmfoto 2021-08-13 um 22 21 48" src="https://user-images.githubusercontent.com/1243826/129415364-313354f7-d072-459f-be5b-6264fbbb1134.png">
<img width="535" alt="Bildschirmfoto 2021-08-13 um 22 27 37" src="https://user-images.githubusercontent.com/1243826/129415367-9aa42bb5-3206-4a39-b5c1-07de2cb0aaae.png">

### Steps To Reproduce:

- Update from rc3 to rc4

**Comment by mfn** [comment]
The "big" change was the re-introduction of the `method` config key for a schema; but it defaults to [get,post]

https://github.com/rebing/graphql-laravel/pull/810/files

I would imagine this most likely is the culprit, though I wonder how exactly. I tried to make it compatible with what was before and also if you don't provide the `method`, the defaults should make things just work.

And from your route output I see that the get/post methods are setup.

I should also note that I run these changes in production since a few days…

Most likely a clash with the config, can you share more? Fell also free to send it to me privately (e.g. slack) and, maybe I can spot something.

**Comment by mfn** [comment]
I'm pretty sure it's a "config" thing, otherwise test suite would also be broken… I guess I missed something for the upgrade 😬

**Comment by Artem-Schander** [comment]
I've sent you my config on slack

**Comment by Artem-Schander** [comment]
@mfn Thank you for the help.

For anyone stumbling upon the same issue, in my case it was the lowercase definitions for the allowed methods.
It needs to be 
```php
'method' => ['GET', 'POST']
```
insead of
```php
'method' => ['get', 'post']
```

**Comment by mfn** [comment]
Thanks, that sucks.

I've add some docs to make this clearer: https://github.com/rebing/graphql-laravel/commit/086c9994d5c549b5884541f6b3d7dcfe8651512e and also added a stanca to the rc4 release notes.

It's a bit annoying, because previously (before rewriting the route code) the verbs were used to directly invoke method calls, so `get` or `gEt` etc. didn't matter.

Now they're passed to `\Illuminate\Routing\Router::addRoute` directly and, apparently, this logic there is all case-sensitive / upper case. I mean even the code in https://github.com/laravel/framework/blob/8.x/src/Illuminate/Routing/Route.php#L173 does direct string matches and it's all expected in upper case.

Sorry for your troubles

**Comment by Artem-Schander** [comment]
No worries. I had no trouble. I've noticed it on my local machine at home .. production and staging are behind a CI pipeline which detects such things. so everything is fine :)
